name: Calendar Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 添加写入权限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync calendar
      env:
        TOGGLE_CALENDAR_URL: ${{ secrets.TOGGLE_CALENDAR_URL }}
      run: python sync_calendar.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add calendar.ics
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar data" && git push)
