name: Update Calendar

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main  # 或者是您的默认分支名称

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests icalendar pytz

    - name: Update calendar
      run: python update_calendar.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add calendar.ics
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar: $(date +'%Y-%m-%d %H:%M:%S')" && git push)
